# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53dac37446f5c2902cefba8302c78687d94236ca58a2d65c9f2d9de4fc9e49c6a1feca2d8f86a57f623455c68452b0ff71f1f265238ea93df24450fb98c85c49

test:
  secret_key_base: 58cf8417ffbf5b1c75ac95892d43ed6a1efacd180dd40932489c614d12948861c8adae4c22b51952270f441cd5161635a6f82c0ae9dc48c65ccf211cbbb529e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
